11. Декоративные элементы на главной странице
htmlacademy-htmlcss/1658897-nerds-30 pull request #10
Opened 2021-03-07 20:42 UTC by Sobolia10

2021-03-09 06:46 UTC, mkolotovich requested changes
Установите браузерное расширение PerfectPixel. Наложите в нём превью макета на сайт и сверстайте так, чтобы расхождения с макетом были в пределах допустимых критериями.

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
> -  padding-top: 49px;
Верните обратно это свойство

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
> +  grid-template-columns: 160px 437px 1fr;
Измените на     grid-template-columns: 160px 437px auto; и задайте     justify-content: space-between;

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
>    height: 111px;
Задайте font-weight: 500;

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
> -  font-weight: 500;
Верните это свойство

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
> +  /*margin-right: 157px;*/
Задайте     padding-top: 17px;    box-sizing: border-box; border-radius: 3px;     margin-bottom: 50px;

2021-03-09 06:46 UTC, mkolotovich commented on css/style.css
>  .slogan {
Задайте color: #000000;

2021-03-11 07:21 UTC, mkolotovich commented on css/style.css
> +  outline: 5px solid #ff0000;
Уберите аутлайны их нет в макете

2021-03-11 07:21 UTC, mkolotovich commented on css/style.css
> +  margin: 47px 0 84px 1px;
Задайте     padding-bottom: 15px; и уберите нижний внешний отступ

2021-03-11 07:21 UTC, mkolotovich commented on catalog.html
> +    <button class="modal-close" type="button">✕</button>
Вместо символа используйте изображение

2021-03-11 07:21 UTC, mkolotovich commented on css/style.css
>  .slogan {
Уберите из селектора .slider-preview, .featured-item, .content p, .benefits-item, .table-item-text селектор .content p

2021-03-11 07:39 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с прошлой проверки

2021-03-12 09:14 UTC, mkolotovich requested changes
Создайте селектор .benefits-item и задайте ему     position: relative;. Создайте селектор .benefits-item::before и задайте ему     content: "";
    position: absolute;
    width: 25px;
    height: 2px;
    left: -32px;
    background: #FB565A;
    top: 12px;
Селектору .footer-contacts задайте     max-width: 1440px;
    margin: auto;
Создайте селектор .social-button a и задайте ему margin: auto;

2021-03-12 09:14 UTC, mkolotovich commented on css/style.css
> -  margin-right: 140px;
Задайте max-width: 1160px;
    margin: auto;

2021-03-12 09:14 UTC, mkolotovich commented on css/style.css
> +  left: 240px;
Уберите это свойство

2021-03-12 09:14 UTC, mkolotovich commented on css/style.css
>  .social-button {
Задайте display: flex;

2021-03-16 11:14 UTC, mkolotovich requested changes
Исправляйте замечания с прошлых проверок

2021-03-17 14:55 UTC, mkolotovich requested changes
А рамки делайте черз псевдоэлементы. В селекторе .contacts-map-marker уберите дичь с отступами, а позиционирование сделайте с помощью свойств left и top например.

2021-03-17 14:55 UTC, mkolotovich commented on css/style.css
> +  /*padding-left: 16px;*/
Верните это свойство. Только измените значение на 14, так как там еще рамка в 2px

2021-03-17 14:55 UTC, mkolotovich commented on css/style.css
>  .login-item-text input {
Здесь тоже задайте padding-left: 14px;

2021-03-17 14:55 UTC, mkolotovich commented on index.html
> -      </textarea>
Верните обратно textarea

2021-03-19 21:05 UTC, mkolotovich commented on css/style.css
> +  /*padding-left: 16px;*/
Здесь я имел ввиду только последнее свойство под которым сделан комментарий, т.е. padding-left: 16px;

2021-03-19 21:23 UTC, mkolotovich requested changes
Исправьте не схлопнутые замечания с прошлой проверки. В макет-то вы попали(кроме модалки) это класс, но вот одна беда есть критерий Б13., который гласит - Сайт нормально смотрится на минимальном для макета разрешении(https://up.htmlacademy.ru/htmlcss/30/criteries#b13). Попробуйте уменьшить разрешение сайта до 1200 и посмотрите как смотрится ваш сайт. Он явно не проходит по этому критерию(

2021-03-21 14:21 UTC, mkolotovich requested changes
Исправьте не схлопнутое замечание тз предыдущих проверок. У селектора @media (max-width: 1200px) .features уберите боковые отступы. У селектора .login-item-text уберите  свойства resize: none; padding-left: 14px; padding-top: 14px; border: 2px solid var(--active-grey);. Селектору .features-button задайте border-radius: 3px;. Селектору .site-navigation a, .basket-navigation a задайте     font-weight: 500;. У селектора .social-button уберите свойство     margin: auto 9px auto auto;

2021-03-21 14:56 UTC, Sobolia10 commented on css/style.css
>  .login-item-text input {
+

2021-03-21 14:57 UTC, Sobolia10 commented on css/style.css
>  .login-item-text input {
сделала.

2021-03-21 15:07 UTC, Sobolia10 commented on index.html
> -      </textarea>
сделала

2021-03-21 15:13 UTC, Sobolia10 commented on css/style.css
> +  left: 240px;
сделала

2021-03-21 15:14 UTC, Sobolia10 commented on css/style.css
> +  /*padding-bottom: 80px;*/
сделала

2021-03-21 15:16 UTC, Sobolia10 commented on css/style.css
> -  margin: 0 240px 180px 240px;
сделала

2021-03-21 15:17 UTC, Sobolia10 commented on catalog.html
> +    <button class="modal-close" type="button">✕</button>
сделала

2021-03-21 15:18 UTC, Sobolia10 commented on css/style.css
> +  margin: 47px 0 84px 1px;
сделала

2021-03-21 15:18 UTC, Sobolia10 commented on css/style.css
> +  outline: 5px solid #ff0000;
сделала

2021-03-21 15:19 UTC, Sobolia10 commented on css/style.css
> +  /*margin-right: 157px;*/
сделала

2021-03-21 15:20 UTC, Sobolia10 commented on css/style.css
> +  grid-template-columns: 160px 437px 1fr;
сделала

2021-03-21 15:23 UTC, Sobolia10 commented on css/style.css
> +  /*padding-left: 16px;*/
сделала

2021-03-22 12:44 UTC, mkolotovich commented on css/style.css
>  .login-item-text input {
Сделали, но не до конца. Одно свойство пропустили.

2021-03-22 12:59 UTC, Sobolia10 commented on css/style.css
>    margin: 80px auto 75px;
сделала

2021-03-22 13:03 UTC, Sobolia10 commented on css/style.css
>  .login-item-text input {
сделала

2021-03-22 13:10 UTC, Sobolia10 commented on css/style.css
>  .login-item-text input {
resize:none добавила)

2021-03-22 13:13 UTC, mkolotovich requested changes
Исправьте не схлопнутое замечание с прошлых проверок. В макет не попали модалка и блок .partners-list. У селектора .html-academy уберите свойства padding-right: 5px;
    margin-left: 25px; и задfйте     padding-right: 13px;. А селектору .barber задайте margin-left: 8px;. Селектору .pink задайте     padding-right: 16px; Селектору .mishka задайте     margin-right: 43px;     margin-top: 4px;

2021-03-22 13:13 UTC, mkolotovich commented on css/style.css
> -/*.login-item-text {*/
Этому селектору задайте     margin-top: 19px

2021-03-22 13:19 UTC, Sobolia10 commented on css/style.css
> -/*.login-item-text {*/
сделала

2021-03-23 04:42 UTC, mkolotovich commented on css/style.css
>  .login-item-text input {
Добавили, но опять не туда. Вы добавили это свойство параграфу-обёртке, а нужно было задать его textarea. Оно служит для того чтобы нельзя было изменять размер textarea, как на макете, а иначе в правом нижнем углу появляется ползунок за который можно его тянть и изменять размер.

2021-03-23 11:38 UTC, mkolotovich commented on css/style.css
> -/*.login-item-text {*/
Вы опять не тому селектору задали свойство. Я писал о селекторе .login-item-text, а вы задали это свойство селектору .login-item-email input,.login-item-user input

2021-03-23 11:56 UTC, mkolotovich requested changes
Исправьте не схлопнутое замечание с предыдущих проверок. Селектору .main-header-logo задайте     margin-top: -11px;. Селектору .basket-navigation a задайте     display: block;     margin-top: -9px;. Селектору .icon-basket задайте     margin-top: 8px;    display: inline-flex;. Селектору .benefits-item::before задайте     left: -35px;

2021-03-23 20:35 UTC, mkolotovich reviewed
Всё отлично только в следующем задании на главной странице у первого элемента списка site-navigation уберите класс menu-active, чтобы вёрстка соответствовала макету.

2021-03-23 20:36 UTC, merged